// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.2
// source: management.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BobcaygeonManagement_GetSpeakers_FullMethodName              = "/BobcaygeonManagement/GetSpeakers"
	BobcaygeonManagement_SetDisplayNameForSpeaker_FullMethodName = "/BobcaygeonManagement/SetDisplayNameForSpeaker"
	BobcaygeonManagement_CreateZone_FullMethodName               = "/BobcaygeonManagement/CreateZone"
	BobcaygeonManagement_AddSpeakersToZone_FullMethodName        = "/BobcaygeonManagement/AddSpeakersToZone"
	BobcaygeonManagement_RemoveSpeakersFromZone_FullMethodName   = "/BobcaygeonManagement/RemoveSpeakersFromZone"
	BobcaygeonManagement_DeleteZone_FullMethodName               = "/BobcaygeonManagement/DeleteZone"
	BobcaygeonManagement_ChangeZoneName_FullMethodName           = "/BobcaygeonManagement/ChangeZoneName"
	BobcaygeonManagement_GetZones_FullMethodName                 = "/BobcaygeonManagement/GetZones"
	BobcaygeonManagement_GetCurrentTrack_FullMethodName          = "/BobcaygeonManagement/GetCurrentTrack"
	BobcaygeonManagement_SetMuteForSpeaker_FullMethodName        = "/BobcaygeonManagement/SetMuteForSpeaker"
	BobcaygeonManagement_GetMuteForSpeaker_FullMethodName        = "/BobcaygeonManagement/GetMuteForSpeaker"
)

// BobcaygeonManagementClient is the client API for BobcaygeonManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BobcaygeonManagementClient interface {
	GetSpeakers(ctx context.Context, in *GetSpeakersRequest, opts ...grpc.CallOption) (*GetSpeakersResponse, error)
	SetDisplayNameForSpeaker(ctx context.Context, in *SetSpeakerDisplayNameRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	CreateZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	AddSpeakersToZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	RemoveSpeakersFromZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	ChangeZoneName(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	GetZones(ctx context.Context, in *GetZonesRequest, opts ...grpc.CallOption) (*GetZonesResponse, error)
	GetCurrentTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*Track, error)
	SetMuteForSpeaker(ctx context.Context, in *SetMuteRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	GetMuteForSpeaker(ctx context.Context, in *GetMuteRequest, opts ...grpc.CallOption) (*SpeakerMuteResponse, error)
}

type bobcaygeonManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewBobcaygeonManagementClient(cc grpc.ClientConnInterface) BobcaygeonManagementClient {
	return &bobcaygeonManagementClient{cc}
}

func (c *bobcaygeonManagementClient) GetSpeakers(ctx context.Context, in *GetSpeakersRequest, opts ...grpc.CallOption) (*GetSpeakersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpeakersResponse)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_GetSpeakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobcaygeonManagementClient) SetDisplayNameForSpeaker(ctx context.Context, in *SetSpeakerDisplayNameRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_SetDisplayNameForSpeaker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobcaygeonManagementClient) CreateZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_CreateZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobcaygeonManagementClient) AddSpeakersToZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_AddSpeakersToZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobcaygeonManagementClient) RemoveSpeakersFromZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_RemoveSpeakersFromZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobcaygeonManagementClient) DeleteZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_DeleteZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobcaygeonManagementClient) ChangeZoneName(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_ChangeZoneName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobcaygeonManagementClient) GetZones(ctx context.Context, in *GetZonesRequest, opts ...grpc.CallOption) (*GetZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetZonesResponse)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_GetZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobcaygeonManagementClient) GetCurrentTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*Track, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Track)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_GetCurrentTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobcaygeonManagementClient) SetMuteForSpeaker(ctx context.Context, in *SetMuteRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_SetMuteForSpeaker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bobcaygeonManagementClient) GetMuteForSpeaker(ctx context.Context, in *GetMuteRequest, opts ...grpc.CallOption) (*SpeakerMuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpeakerMuteResponse)
	err := c.cc.Invoke(ctx, BobcaygeonManagement_GetMuteForSpeaker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BobcaygeonManagementServer is the server API for BobcaygeonManagement service.
// All implementations must embed UnimplementedBobcaygeonManagementServer
// for forward compatibility.
type BobcaygeonManagementServer interface {
	GetSpeakers(context.Context, *GetSpeakersRequest) (*GetSpeakersResponse, error)
	SetDisplayNameForSpeaker(context.Context, *SetSpeakerDisplayNameRequest) (*UpdateResponse, error)
	CreateZone(context.Context, *ZoneRequest) (*CreateResponse, error)
	AddSpeakersToZone(context.Context, *ZoneRequest) (*UpdateResponse, error)
	RemoveSpeakersFromZone(context.Context, *ZoneRequest) (*UpdateResponse, error)
	DeleteZone(context.Context, *ZoneRequest) (*UpdateResponse, error)
	ChangeZoneName(context.Context, *ZoneRequest) (*UpdateResponse, error)
	GetZones(context.Context, *GetZonesRequest) (*GetZonesResponse, error)
	GetCurrentTrack(context.Context, *GetTrackRequest) (*Track, error)
	SetMuteForSpeaker(context.Context, *SetMuteRequest) (*UpdateResponse, error)
	GetMuteForSpeaker(context.Context, *GetMuteRequest) (*SpeakerMuteResponse, error)
	mustEmbedUnimplementedBobcaygeonManagementServer()
}

// UnimplementedBobcaygeonManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBobcaygeonManagementServer struct{}

func (UnimplementedBobcaygeonManagementServer) GetSpeakers(context.Context, *GetSpeakersRequest) (*GetSpeakersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpeakers not implemented")
}
func (UnimplementedBobcaygeonManagementServer) SetDisplayNameForSpeaker(context.Context, *SetSpeakerDisplayNameRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDisplayNameForSpeaker not implemented")
}
func (UnimplementedBobcaygeonManagementServer) CreateZone(context.Context, *ZoneRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateZone not implemented")
}
func (UnimplementedBobcaygeonManagementServer) AddSpeakersToZone(context.Context, *ZoneRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSpeakersToZone not implemented")
}
func (UnimplementedBobcaygeonManagementServer) RemoveSpeakersFromZone(context.Context, *ZoneRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSpeakersFromZone not implemented")
}
func (UnimplementedBobcaygeonManagementServer) DeleteZone(context.Context, *ZoneRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteZone not implemented")
}
func (UnimplementedBobcaygeonManagementServer) ChangeZoneName(context.Context, *ZoneRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeZoneName not implemented")
}
func (UnimplementedBobcaygeonManagementServer) GetZones(context.Context, *GetZonesRequest) (*GetZonesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetZones not implemented")
}
func (UnimplementedBobcaygeonManagementServer) GetCurrentTrack(context.Context, *GetTrackRequest) (*Track, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentTrack not implemented")
}
func (UnimplementedBobcaygeonManagementServer) SetMuteForSpeaker(context.Context, *SetMuteRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMuteForSpeaker not implemented")
}
func (UnimplementedBobcaygeonManagementServer) GetMuteForSpeaker(context.Context, *GetMuteRequest) (*SpeakerMuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMuteForSpeaker not implemented")
}
func (UnimplementedBobcaygeonManagementServer) mustEmbedUnimplementedBobcaygeonManagementServer() {}
func (UnimplementedBobcaygeonManagementServer) testEmbeddedByValue()                              {}

// UnsafeBobcaygeonManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BobcaygeonManagementServer will
// result in compilation errors.
type UnsafeBobcaygeonManagementServer interface {
	mustEmbedUnimplementedBobcaygeonManagementServer()
}

func RegisterBobcaygeonManagementServer(s grpc.ServiceRegistrar, srv BobcaygeonManagementServer) {
	// If the following call pancis, it indicates UnimplementedBobcaygeonManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BobcaygeonManagement_ServiceDesc, srv)
}

func _BobcaygeonManagement_GetSpeakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpeakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).GetSpeakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_GetSpeakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).GetSpeakers(ctx, req.(*GetSpeakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobcaygeonManagement_SetDisplayNameForSpeaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSpeakerDisplayNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).SetDisplayNameForSpeaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_SetDisplayNameForSpeaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).SetDisplayNameForSpeaker(ctx, req.(*SetSpeakerDisplayNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobcaygeonManagement_CreateZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).CreateZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_CreateZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).CreateZone(ctx, req.(*ZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobcaygeonManagement_AddSpeakersToZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).AddSpeakersToZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_AddSpeakersToZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).AddSpeakersToZone(ctx, req.(*ZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobcaygeonManagement_RemoveSpeakersFromZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).RemoveSpeakersFromZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_RemoveSpeakersFromZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).RemoveSpeakersFromZone(ctx, req.(*ZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobcaygeonManagement_DeleteZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).DeleteZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_DeleteZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).DeleteZone(ctx, req.(*ZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobcaygeonManagement_ChangeZoneName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).ChangeZoneName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_ChangeZoneName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).ChangeZoneName(ctx, req.(*ZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobcaygeonManagement_GetZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).GetZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_GetZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).GetZones(ctx, req.(*GetZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobcaygeonManagement_GetCurrentTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).GetCurrentTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_GetCurrentTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).GetCurrentTrack(ctx, req.(*GetTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobcaygeonManagement_SetMuteForSpeaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).SetMuteForSpeaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_SetMuteForSpeaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).SetMuteForSpeaker(ctx, req.(*SetMuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BobcaygeonManagement_GetMuteForSpeaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobcaygeonManagementServer).GetMuteForSpeaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BobcaygeonManagement_GetMuteForSpeaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobcaygeonManagementServer).GetMuteForSpeaker(ctx, req.(*GetMuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BobcaygeonManagement_ServiceDesc is the grpc.ServiceDesc for BobcaygeonManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BobcaygeonManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BobcaygeonManagement",
	HandlerType: (*BobcaygeonManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpeakers",
			Handler:    _BobcaygeonManagement_GetSpeakers_Handler,
		},
		{
			MethodName: "SetDisplayNameForSpeaker",
			Handler:    _BobcaygeonManagement_SetDisplayNameForSpeaker_Handler,
		},
		{
			MethodName: "CreateZone",
			Handler:    _BobcaygeonManagement_CreateZone_Handler,
		},
		{
			MethodName: "AddSpeakersToZone",
			Handler:    _BobcaygeonManagement_AddSpeakersToZone_Handler,
		},
		{
			MethodName: "RemoveSpeakersFromZone",
			Handler:    _BobcaygeonManagement_RemoveSpeakersFromZone_Handler,
		},
		{
			MethodName: "DeleteZone",
			Handler:    _BobcaygeonManagement_DeleteZone_Handler,
		},
		{
			MethodName: "ChangeZoneName",
			Handler:    _BobcaygeonManagement_ChangeZoneName_Handler,
		},
		{
			MethodName: "GetZones",
			Handler:    _BobcaygeonManagement_GetZones_Handler,
		},
		{
			MethodName: "GetCurrentTrack",
			Handler:    _BobcaygeonManagement_GetCurrentTrack_Handler,
		},
		{
			MethodName: "SetMuteForSpeaker",
			Handler:    _BobcaygeonManagement_SetMuteForSpeaker_Handler,
		},
		{
			MethodName: "GetMuteForSpeaker",
			Handler:    _BobcaygeonManagement_GetMuteForSpeaker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management.proto",
}
