// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.2
// source: management.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Speaker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Speaker) Reset() {
	*x = Speaker{}
	mi := &file_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Speaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Speaker) ProtoMessage() {}

func (x *Speaker) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Speaker.ProtoReflect.Descriptor instead.
func (*Speaker) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{0}
}

func (x *Speaker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Speaker) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Speakers      []*Speaker             `protobuf:"bytes,3,rep,name=speakers,proto3" json:"speakers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{1}
}

func (x *Zone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Zone) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Zone) GetSpeakers() []*Speaker {
	if x != nil {
		return x.Speakers
	}
	return nil
}

type GetSpeakersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speakers      []*Speaker             `protobuf:"bytes,1,rep,name=speakers,proto3" json:"speakers,omitempty"`
	ReturnCode    int32                  `protobuf:"varint,2,opt,name=returnCode,proto3" json:"returnCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpeakersResponse) Reset() {
	*x = GetSpeakersResponse{}
	mi := &file_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpeakersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpeakersResponse) ProtoMessage() {}

func (x *GetSpeakersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpeakersResponse.ProtoReflect.Descriptor instead.
func (*GetSpeakersResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{2}
}

func (x *GetSpeakersResponse) GetSpeakers() []*Speaker {
	if x != nil {
		return x.Speakers
	}
	return nil
}

func (x *GetSpeakersResponse) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

type GetSpeakersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpeakerId     string                 `protobuf:"bytes,1,opt,name=speakerId,proto3" json:"speakerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpeakersRequest) Reset() {
	*x = GetSpeakersRequest{}
	mi := &file_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpeakersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpeakersRequest) ProtoMessage() {}

func (x *GetSpeakersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpeakersRequest.ProtoReflect.Descriptor instead.
func (*GetSpeakersRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{3}
}

func (x *GetSpeakersRequest) GetSpeakerId() string {
	if x != nil {
		return x.SpeakerId
	}
	return ""
}

type SetSpeakerDisplayNameRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SpeakerId       string                 `protobuf:"bytes,1,opt,name=speakerId,proto3" json:"speakerId,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	UpdateBroadcast bool                   `protobuf:"varint,3,opt,name=updateBroadcast,proto3" json:"updateBroadcast,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetSpeakerDisplayNameRequest) Reset() {
	*x = SetSpeakerDisplayNameRequest{}
	mi := &file_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpeakerDisplayNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpeakerDisplayNameRequest) ProtoMessage() {}

func (x *SetSpeakerDisplayNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpeakerDisplayNameRequest.ProtoReflect.Descriptor instead.
func (*SetSpeakerDisplayNameRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{4}
}

func (x *SetSpeakerDisplayNameRequest) GetSpeakerId() string {
	if x != nil {
		return x.SpeakerId
	}
	return ""
}

func (x *SetSpeakerDisplayNameRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SetSpeakerDisplayNameRequest) GetUpdateBroadcast() bool {
	if x != nil {
		return x.UpdateBroadcast
	}
	return false
}

type ZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	SpeakerIds    []string               `protobuf:"bytes,3,rep,name=speakerIds,proto3" json:"speakerIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneRequest) Reset() {
	*x = ZoneRequest{}
	mi := &file_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneRequest) ProtoMessage() {}

func (x *ZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneRequest.ProtoReflect.Descriptor instead.
func (*ZoneRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{5}
}

func (x *ZoneRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ZoneRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ZoneRequest) GetSpeakerIds() []string {
	if x != nil {
		return x.SpeakerIds
	}
	return nil
}

type GetZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZonesRequest) Reset() {
	*x = GetZonesRequest{}
	mi := &file_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZonesRequest) ProtoMessage() {}

func (x *GetZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZonesRequest.ProtoReflect.Descriptor instead.
func (*GetZonesRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{6}
}

func (x *GetZonesRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type GetTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	SpeakerId     string                 `protobuf:"bytes,2,opt,name=speakerId,proto3" json:"speakerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackRequest) Reset() {
	*x = GetTrackRequest{}
	mi := &file_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackRequest) ProtoMessage() {}

func (x *GetTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackRequest.ProtoReflect.Descriptor instead.
func (*GetTrackRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{7}
}

func (x *GetTrackRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *GetTrackRequest) GetSpeakerId() string {
	if x != nil {
		return x.SpeakerId
	}
	return ""
}

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        string                 `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,2,opt,name=album,proto3" json:"album,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Artwork       []byte                 `protobuf:"bytes,4,opt,name=artwork,proto3" json:"artwork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{8}
}

func (x *Track) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Track) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetArtwork() []byte {
	if x != nil {
		return x.Artwork
	}
	return nil
}

type SetMuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpeakerId     string                 `protobuf:"bytes,1,opt,name=speakerId,proto3" json:"speakerId,omitempty"`
	IsMuted       bool                   `protobuf:"varint,2,opt,name=isMuted,proto3" json:"isMuted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMuteRequest) Reset() {
	*x = SetMuteRequest{}
	mi := &file_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMuteRequest) ProtoMessage() {}

func (x *SetMuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMuteRequest.ProtoReflect.Descriptor instead.
func (*SetMuteRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{9}
}

func (x *SetMuteRequest) GetSpeakerId() string {
	if x != nil {
		return x.SpeakerId
	}
	return ""
}

func (x *SetMuteRequest) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

type GetMuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpeakerId     string                 `protobuf:"bytes,1,opt,name=speakerId,proto3" json:"speakerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMuteRequest) Reset() {
	*x = GetMuteRequest{}
	mi := &file_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMuteRequest) ProtoMessage() {}

func (x *GetMuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMuteRequest.ProtoReflect.Descriptor instead.
func (*GetMuteRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{10}
}

func (x *GetMuteRequest) GetSpeakerId() string {
	if x != nil {
		return x.SpeakerId
	}
	return ""
}

type SpeakerMuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMuted       bool                   `protobuf:"varint,1,opt,name=isMuted,proto3" json:"isMuted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeakerMuteResponse) Reset() {
	*x = SpeakerMuteResponse{}
	mi := &file_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakerMuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakerMuteResponse) ProtoMessage() {}

func (x *SpeakerMuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakerMuteResponse.ProtoReflect.Descriptor instead.
func (*SpeakerMuteResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{11}
}

func (x *SpeakerMuteResponse) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

type GetZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*Zone                `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	ReturnCode    int32                  `protobuf:"varint,2,opt,name=returnCode,proto3" json:"returnCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZonesResponse) Reset() {
	*x = GetZonesResponse{}
	mi := &file_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZonesResponse) ProtoMessage() {}

func (x *GetZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZonesResponse.ProtoReflect.Descriptor instead.
func (*GetZonesResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{12}
}

func (x *GetZonesResponse) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *GetZonesResponse) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseCode  int32                  `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{13}
}

func (x *CreateResponse) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseCode  int32                  `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateResponse) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_management_proto protoreflect.FileDescriptor

const file_management_proto_rawDesc = "" +
	"\n" +
	"\x10management.proto\";\n" +
	"\aSpeaker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\"^\n" +
	"\x04Zone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\x12$\n" +
	"\bspeakers\x18\x03 \x03(\v2\b.SpeakerR\bspeakers\"[\n" +
	"\x13GetSpeakersResponse\x12$\n" +
	"\bspeakers\x18\x01 \x03(\v2\b.SpeakerR\bspeakers\x12\x1e\n" +
	"\n" +
	"returnCode\x18\x02 \x01(\x05R\n" +
	"returnCode\"2\n" +
	"\x12GetSpeakersRequest\x12\x1c\n" +
	"\tspeakerId\x18\x01 \x01(\tR\tspeakerId\"\x88\x01\n" +
	"\x1cSetSpeakerDisplayNameRequest\x12\x1c\n" +
	"\tspeakerId\x18\x01 \x01(\tR\tspeakerId\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\x12(\n" +
	"\x0fupdateBroadcast\x18\x03 \x01(\bR\x0fupdateBroadcast\"g\n" +
	"\vZoneRequest\x12\x16\n" +
	"\x06zoneId\x18\x01 \x01(\tR\x06zoneId\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\x12\x1e\n" +
	"\n" +
	"speakerIds\x18\x03 \x03(\tR\n" +
	"speakerIds\")\n" +
	"\x0fGetZonesRequest\x12\x16\n" +
	"\x06zoneId\x18\x01 \x01(\tR\x06zoneId\"G\n" +
	"\x0fGetTrackRequest\x12\x16\n" +
	"\x06zoneId\x18\x01 \x01(\tR\x06zoneId\x12\x1c\n" +
	"\tspeakerId\x18\x02 \x01(\tR\tspeakerId\"e\n" +
	"\x05Track\x12\x16\n" +
	"\x06artist\x18\x01 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x02 \x01(\tR\x05album\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\aartwork\x18\x04 \x01(\fR\aartwork\"H\n" +
	"\x0eSetMuteRequest\x12\x1c\n" +
	"\tspeakerId\x18\x01 \x01(\tR\tspeakerId\x12\x18\n" +
	"\aisMuted\x18\x02 \x01(\bR\aisMuted\".\n" +
	"\x0eGetMuteRequest\x12\x1c\n" +
	"\tspeakerId\x18\x01 \x01(\tR\tspeakerId\"/\n" +
	"\x13SpeakerMuteResponse\x12\x18\n" +
	"\aisMuted\x18\x01 \x01(\bR\aisMuted\"O\n" +
	"\x10GetZonesResponse\x12\x1b\n" +
	"\x05zones\x18\x01 \x03(\v2\x05.ZoneR\x05zones\x12\x1e\n" +
	"\n" +
	"returnCode\x18\x02 \x01(\x05R\n" +
	"returnCode\"^\n" +
	"\x0eCreateResponse\x12\"\n" +
	"\fresponseCode\x18\x01 \x01(\x05R\fresponseCode\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"N\n" +
	"\x0eUpdateResponse\x12\"\n" +
	"\fresponseCode\x18\x01 \x01(\x05R\fresponseCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfb\x04\n" +
	"\x14BobcaygeonManagement\x12:\n" +
	"\vGetSpeakers\x12\x13.GetSpeakersRequest\x1a\x14.GetSpeakersResponse\"\x00\x12L\n" +
	"\x18SetDisplayNameForSpeaker\x12\x1d.SetSpeakerDisplayNameRequest\x1a\x0f.UpdateResponse\"\x00\x12-\n" +
	"\n" +
	"CreateZone\x12\f.ZoneRequest\x1a\x0f.CreateResponse\"\x00\x124\n" +
	"\x11AddSpeakersToZone\x12\f.ZoneRequest\x1a\x0f.UpdateResponse\"\x00\x129\n" +
	"\x16RemoveSpeakersFromZone\x12\f.ZoneRequest\x1a\x0f.UpdateResponse\"\x00\x12-\n" +
	"\n" +
	"DeleteZone\x12\f.ZoneRequest\x1a\x0f.UpdateResponse\"\x00\x121\n" +
	"\x0eChangeZoneName\x12\f.ZoneRequest\x1a\x0f.UpdateResponse\"\x00\x121\n" +
	"\bGetZones\x12\x10.GetZonesRequest\x1a\x11.GetZonesResponse\"\x00\x12-\n" +
	"\x0fGetCurrentTrack\x12\x10.GetTrackRequest\x1a\x06.Track\"\x00\x127\n" +
	"\x11SetMuteForSpeaker\x12\x0f.SetMuteRequest\x1a\x0f.UpdateResponse\"\x00\x12<\n" +
	"\x11GetMuteForSpeaker\x12\x0f.GetMuteRequest\x1a\x14.SpeakerMuteResponse\"\x00B\bZ\x06./;apib\x06proto3"

var (
	file_management_proto_rawDescOnce sync.Once
	file_management_proto_rawDescData []byte
)

func file_management_proto_rawDescGZIP() []byte {
	file_management_proto_rawDescOnce.Do(func() {
		file_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)))
	})
	return file_management_proto_rawDescData
}

var file_management_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_management_proto_goTypes = []any{
	(*Speaker)(nil),                      // 0: Speaker
	(*Zone)(nil),                         // 1: Zone
	(*GetSpeakersResponse)(nil),          // 2: GetSpeakersResponse
	(*GetSpeakersRequest)(nil),           // 3: GetSpeakersRequest
	(*SetSpeakerDisplayNameRequest)(nil), // 4: SetSpeakerDisplayNameRequest
	(*ZoneRequest)(nil),                  // 5: ZoneRequest
	(*GetZonesRequest)(nil),              // 6: GetZonesRequest
	(*GetTrackRequest)(nil),              // 7: GetTrackRequest
	(*Track)(nil),                        // 8: Track
	(*SetMuteRequest)(nil),               // 9: SetMuteRequest
	(*GetMuteRequest)(nil),               // 10: GetMuteRequest
	(*SpeakerMuteResponse)(nil),          // 11: SpeakerMuteResponse
	(*GetZonesResponse)(nil),             // 12: GetZonesResponse
	(*CreateResponse)(nil),               // 13: CreateResponse
	(*UpdateResponse)(nil),               // 14: UpdateResponse
}
var file_management_proto_depIdxs = []int32{
	0,  // 0: Zone.speakers:type_name -> Speaker
	0,  // 1: GetSpeakersResponse.speakers:type_name -> Speaker
	1,  // 2: GetZonesResponse.zones:type_name -> Zone
	3,  // 3: BobcaygeonManagement.GetSpeakers:input_type -> GetSpeakersRequest
	4,  // 4: BobcaygeonManagement.SetDisplayNameForSpeaker:input_type -> SetSpeakerDisplayNameRequest
	5,  // 5: BobcaygeonManagement.CreateZone:input_type -> ZoneRequest
	5,  // 6: BobcaygeonManagement.AddSpeakersToZone:input_type -> ZoneRequest
	5,  // 7: BobcaygeonManagement.RemoveSpeakersFromZone:input_type -> ZoneRequest
	5,  // 8: BobcaygeonManagement.DeleteZone:input_type -> ZoneRequest
	5,  // 9: BobcaygeonManagement.ChangeZoneName:input_type -> ZoneRequest
	6,  // 10: BobcaygeonManagement.GetZones:input_type -> GetZonesRequest
	7,  // 11: BobcaygeonManagement.GetCurrentTrack:input_type -> GetTrackRequest
	9,  // 12: BobcaygeonManagement.SetMuteForSpeaker:input_type -> SetMuteRequest
	10, // 13: BobcaygeonManagement.GetMuteForSpeaker:input_type -> GetMuteRequest
	2,  // 14: BobcaygeonManagement.GetSpeakers:output_type -> GetSpeakersResponse
	14, // 15: BobcaygeonManagement.SetDisplayNameForSpeaker:output_type -> UpdateResponse
	13, // 16: BobcaygeonManagement.CreateZone:output_type -> CreateResponse
	14, // 17: BobcaygeonManagement.AddSpeakersToZone:output_type -> UpdateResponse
	14, // 18: BobcaygeonManagement.RemoveSpeakersFromZone:output_type -> UpdateResponse
	14, // 19: BobcaygeonManagement.DeleteZone:output_type -> UpdateResponse
	14, // 20: BobcaygeonManagement.ChangeZoneName:output_type -> UpdateResponse
	12, // 21: BobcaygeonManagement.GetZones:output_type -> GetZonesResponse
	8,  // 22: BobcaygeonManagement.GetCurrentTrack:output_type -> Track
	14, // 23: BobcaygeonManagement.SetMuteForSpeaker:output_type -> UpdateResponse
	11, // 24: BobcaygeonManagement.GetMuteForSpeaker:output_type -> SpeakerMuteResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_management_proto_init() }
func file_management_proto_init() {
	if File_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_proto_goTypes,
		DependencyIndexes: file_management_proto_depIdxs,
		MessageInfos:      file_management_proto_msgTypes,
	}.Build()
	File_management_proto = out.File
	file_management_proto_goTypes = nil
	file_management_proto_depIdxs = nil
}
