// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.2
// source: bobcaygeon.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRemoveNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	RemoveAll     bool                   `protobuf:"varint,2,opt,name=removeAll,proto3" json:"removeAll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRemoveNodesRequest) Reset() {
	*x = AddRemoveNodesRequest{}
	mi := &file_bobcaygeon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRemoveNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemoveNodesRequest) ProtoMessage() {}

func (x *AddRemoveNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobcaygeon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemoveNodesRequest.ProtoReflect.Descriptor instead.
func (*AddRemoveNodesRequest) Descriptor() ([]byte, []int) {
	return file_bobcaygeon_proto_rawDescGZIP(), []int{0}
}

func (x *AddRemoveNodesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *AddRemoveNodesRequest) GetRemoveAll() bool {
	if x != nil {
		return x.RemoveAll
	}
	return false
}

type BroadcastRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShouldBroadcast bool                   `protobuf:"varint,1,opt,name=shouldBroadcast,proto3" json:"shouldBroadcast,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_bobcaygeon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobcaygeon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_bobcaygeon_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastRequest) GetShouldBroadcast() bool {
	if x != nil {
		return x.ShouldBroadcast
	}
	return false
}

type NameChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewName       string                 `protobuf:"bytes,1,opt,name=newName,proto3" json:"newName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameChangeRequest) Reset() {
	*x = NameChangeRequest{}
	mi := &file_bobcaygeon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameChangeRequest) ProtoMessage() {}

func (x *NameChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobcaygeon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameChangeRequest.ProtoReflect.Descriptor instead.
func (*NameChangeRequest) Descriptor() ([]byte, []int) {
	return file_bobcaygeon_proto_rawDescGZIP(), []int{2}
}

func (x *NameChangeRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type GetTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackRequest) Reset() {
	*x = GetTrackRequest{}
	mi := &file_bobcaygeon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackRequest) ProtoMessage() {}

func (x *GetTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobcaygeon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackRequest.ProtoReflect.Descriptor instead.
func (*GetTrackRequest) Descriptor() ([]byte, []int) {
	return file_bobcaygeon_proto_rawDescGZIP(), []int{3}
}

type GetMutedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMutedRequest) Reset() {
	*x = GetMutedRequest{}
	mi := &file_bobcaygeon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMutedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMutedRequest) ProtoMessage() {}

func (x *GetMutedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bobcaygeon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMutedRequest.ProtoReflect.Descriptor instead.
func (*GetMutedRequest) Descriptor() ([]byte, []int) {
	return file_bobcaygeon_proto_rawDescGZIP(), []int{4}
}

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        string                 `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,2,opt,name=album,proto3" json:"album,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Artwork       []byte                 `protobuf:"bytes,4,opt,name=artwork,proto3" json:"artwork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_bobcaygeon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_bobcaygeon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_bobcaygeon_proto_rawDescGZIP(), []int{5}
}

func (x *Track) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Track) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetArtwork() []byte {
	if x != nil {
		return x.Artwork
	}
	return nil
}

type ManagementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    int32                  `protobuf:"varint,1,opt,name=returnCode,proto3" json:"returnCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagementResponse) Reset() {
	*x = ManagementResponse{}
	mi := &file_bobcaygeon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagementResponse) ProtoMessage() {}

func (x *ManagementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bobcaygeon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagementResponse.ProtoReflect.Descriptor instead.
func (*ManagementResponse) Descriptor() ([]byte, []int) {
	return file_bobcaygeon_proto_rawDescGZIP(), []int{6}
}

func (x *ManagementResponse) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *ManagementResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SpeakerMuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMuted       bool                   `protobuf:"varint,1,opt,name=isMuted,proto3" json:"isMuted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeakerMuteResponse) Reset() {
	*x = SpeakerMuteResponse{}
	mi := &file_bobcaygeon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakerMuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakerMuteResponse) ProtoMessage() {}

func (x *SpeakerMuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bobcaygeon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakerMuteResponse.ProtoReflect.Descriptor instead.
func (*SpeakerMuteResponse) Descriptor() ([]byte, []int) {
	return file_bobcaygeon_proto_rawDescGZIP(), []int{7}
}

func (x *SpeakerMuteResponse) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

var File_bobcaygeon_proto protoreflect.FileDescriptor

const file_bobcaygeon_proto_rawDesc = "" +
	"\n" +
	"\x10bobcaygeon.proto\x12\x03api\"G\n" +
	"\x15AddRemoveNodesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1c\n" +
	"\tremoveAll\x18\x02 \x01(\bR\tremoveAll\"<\n" +
	"\x10BroadcastRequest\x12(\n" +
	"\x0fshouldBroadcast\x18\x01 \x01(\bR\x0fshouldBroadcast\"-\n" +
	"\x11NameChangeRequest\x12\x18\n" +
	"\anewName\x18\x01 \x01(\tR\anewName\"\x11\n" +
	"\x0fGetTrackRequest\"\x11\n" +
	"\x0fGetMutedRequest\"e\n" +
	"\x05Track\x12\x16\n" +
	"\x06artist\x18\x01 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x02 \x01(\tR\x05album\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\aartwork\x18\x04 \x01(\fR\aartwork\"N\n" +
	"\x12ManagementResponse\x12\x1e\n" +
	"\n" +
	"returnCode\x18\x01 \x01(\x05R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x13SpeakerMuteResponse\x12\x18\n" +
	"\aisMuted\x18\x01 \x01(\bR\aisMuted2\xad\x03\n" +
	"\x11AirPlayManagement\x12C\n" +
	"\x0fToggleBroadcast\x12\x15.api.BroadcastRequest\x1a\x17.api.ManagementResponse\"\x00\x12F\n" +
	"\x11ChangeServiceName\x12\x16.api.NameChangeRequest\x1a\x17.api.ManagementResponse\"\x00\x12G\n" +
	"\x0eForwardToNodes\x12\x1a.api.AddRemoveNodesRequest\x1a\x17.api.ManagementResponse\"\x00\x12M\n" +
	"\x14RemoveForwardToNodes\x12\x1a.api.AddRemoveNodesRequest\x1a\x17.api.ManagementResponse\"\x00\x125\n" +
	"\x0fGetCurrentTrack\x12\x14.api.GetTrackRequest\x1a\n" +
	".api.Track\"\x00\x12<\n" +
	"\bGetMuted\x12\x14.api.GetMutedRequest\x1a\x18.api.SpeakerMuteResponse\"\x00B\bZ\x06./;apib\x06proto3"

var (
	file_bobcaygeon_proto_rawDescOnce sync.Once
	file_bobcaygeon_proto_rawDescData []byte
)

func file_bobcaygeon_proto_rawDescGZIP() []byte {
	file_bobcaygeon_proto_rawDescOnce.Do(func() {
		file_bobcaygeon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bobcaygeon_proto_rawDesc), len(file_bobcaygeon_proto_rawDesc)))
	})
	return file_bobcaygeon_proto_rawDescData
}

var file_bobcaygeon_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bobcaygeon_proto_goTypes = []any{
	(*AddRemoveNodesRequest)(nil), // 0: api.AddRemoveNodesRequest
	(*BroadcastRequest)(nil),      // 1: api.BroadcastRequest
	(*NameChangeRequest)(nil),     // 2: api.NameChangeRequest
	(*GetTrackRequest)(nil),       // 3: api.GetTrackRequest
	(*GetMutedRequest)(nil),       // 4: api.GetMutedRequest
	(*Track)(nil),                 // 5: api.Track
	(*ManagementResponse)(nil),    // 6: api.ManagementResponse
	(*SpeakerMuteResponse)(nil),   // 7: api.SpeakerMuteResponse
}
var file_bobcaygeon_proto_depIdxs = []int32{
	1, // 0: api.AirPlayManagement.ToggleBroadcast:input_type -> api.BroadcastRequest
	2, // 1: api.AirPlayManagement.ChangeServiceName:input_type -> api.NameChangeRequest
	0, // 2: api.AirPlayManagement.ForwardToNodes:input_type -> api.AddRemoveNodesRequest
	0, // 3: api.AirPlayManagement.RemoveForwardToNodes:input_type -> api.AddRemoveNodesRequest
	3, // 4: api.AirPlayManagement.GetCurrentTrack:input_type -> api.GetTrackRequest
	4, // 5: api.AirPlayManagement.GetMuted:input_type -> api.GetMutedRequest
	6, // 6: api.AirPlayManagement.ToggleBroadcast:output_type -> api.ManagementResponse
	6, // 7: api.AirPlayManagement.ChangeServiceName:output_type -> api.ManagementResponse
	6, // 8: api.AirPlayManagement.ForwardToNodes:output_type -> api.ManagementResponse
	6, // 9: api.AirPlayManagement.RemoveForwardToNodes:output_type -> api.ManagementResponse
	5, // 10: api.AirPlayManagement.GetCurrentTrack:output_type -> api.Track
	7, // 11: api.AirPlayManagement.GetMuted:output_type -> api.SpeakerMuteResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bobcaygeon_proto_init() }
func file_bobcaygeon_proto_init() {
	if File_bobcaygeon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bobcaygeon_proto_rawDesc), len(file_bobcaygeon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bobcaygeon_proto_goTypes,
		DependencyIndexes: file_bobcaygeon_proto_depIdxs,
		MessageInfos:      file_bobcaygeon_proto_msgTypes,
	}.Build()
	File_bobcaygeon_proto = out.File
	file_bobcaygeon_proto_goTypes = nil
	file_bobcaygeon_proto_depIdxs = nil
}
