// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.2
// source: bobcaygeon.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AirPlayManagement_ToggleBroadcast_FullMethodName      = "/api.AirPlayManagement/ToggleBroadcast"
	AirPlayManagement_ChangeServiceName_FullMethodName    = "/api.AirPlayManagement/ChangeServiceName"
	AirPlayManagement_ForwardToNodes_FullMethodName       = "/api.AirPlayManagement/ForwardToNodes"
	AirPlayManagement_RemoveForwardToNodes_FullMethodName = "/api.AirPlayManagement/RemoveForwardToNodes"
	AirPlayManagement_GetCurrentTrack_FullMethodName      = "/api.AirPlayManagement/GetCurrentTrack"
	AirPlayManagement_GetMuted_FullMethodName             = "/api.AirPlayManagement/GetMuted"
)

// AirPlayManagementClient is the client API for AirPlayManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirPlayManagementClient interface {
	ToggleBroadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*ManagementResponse, error)
	ChangeServiceName(ctx context.Context, in *NameChangeRequest, opts ...grpc.CallOption) (*ManagementResponse, error)
	ForwardToNodes(ctx context.Context, in *AddRemoveNodesRequest, opts ...grpc.CallOption) (*ManagementResponse, error)
	RemoveForwardToNodes(ctx context.Context, in *AddRemoveNodesRequest, opts ...grpc.CallOption) (*ManagementResponse, error)
	GetCurrentTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*Track, error)
	GetMuted(ctx context.Context, in *GetMutedRequest, opts ...grpc.CallOption) (*SpeakerMuteResponse, error)
}

type airPlayManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewAirPlayManagementClient(cc grpc.ClientConnInterface) AirPlayManagementClient {
	return &airPlayManagementClient{cc}
}

func (c *airPlayManagementClient) ToggleBroadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*ManagementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementResponse)
	err := c.cc.Invoke(ctx, AirPlayManagement_ToggleBroadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airPlayManagementClient) ChangeServiceName(ctx context.Context, in *NameChangeRequest, opts ...grpc.CallOption) (*ManagementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementResponse)
	err := c.cc.Invoke(ctx, AirPlayManagement_ChangeServiceName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airPlayManagementClient) ForwardToNodes(ctx context.Context, in *AddRemoveNodesRequest, opts ...grpc.CallOption) (*ManagementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementResponse)
	err := c.cc.Invoke(ctx, AirPlayManagement_ForwardToNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airPlayManagementClient) RemoveForwardToNodes(ctx context.Context, in *AddRemoveNodesRequest, opts ...grpc.CallOption) (*ManagementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementResponse)
	err := c.cc.Invoke(ctx, AirPlayManagement_RemoveForwardToNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airPlayManagementClient) GetCurrentTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*Track, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Track)
	err := c.cc.Invoke(ctx, AirPlayManagement_GetCurrentTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airPlayManagementClient) GetMuted(ctx context.Context, in *GetMutedRequest, opts ...grpc.CallOption) (*SpeakerMuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpeakerMuteResponse)
	err := c.cc.Invoke(ctx, AirPlayManagement_GetMuted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AirPlayManagementServer is the server API for AirPlayManagement service.
// All implementations must embed UnimplementedAirPlayManagementServer
// for forward compatibility.
type AirPlayManagementServer interface {
	ToggleBroadcast(context.Context, *BroadcastRequest) (*ManagementResponse, error)
	ChangeServiceName(context.Context, *NameChangeRequest) (*ManagementResponse, error)
	ForwardToNodes(context.Context, *AddRemoveNodesRequest) (*ManagementResponse, error)
	RemoveForwardToNodes(context.Context, *AddRemoveNodesRequest) (*ManagementResponse, error)
	GetCurrentTrack(context.Context, *GetTrackRequest) (*Track, error)
	GetMuted(context.Context, *GetMutedRequest) (*SpeakerMuteResponse, error)
	mustEmbedUnimplementedAirPlayManagementServer()
}

// UnimplementedAirPlayManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAirPlayManagementServer struct{}

func (UnimplementedAirPlayManagementServer) ToggleBroadcast(context.Context, *BroadcastRequest) (*ManagementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleBroadcast not implemented")
}
func (UnimplementedAirPlayManagementServer) ChangeServiceName(context.Context, *NameChangeRequest) (*ManagementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeServiceName not implemented")
}
func (UnimplementedAirPlayManagementServer) ForwardToNodes(context.Context, *AddRemoveNodesRequest) (*ManagementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardToNodes not implemented")
}
func (UnimplementedAirPlayManagementServer) RemoveForwardToNodes(context.Context, *AddRemoveNodesRequest) (*ManagementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveForwardToNodes not implemented")
}
func (UnimplementedAirPlayManagementServer) GetCurrentTrack(context.Context, *GetTrackRequest) (*Track, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentTrack not implemented")
}
func (UnimplementedAirPlayManagementServer) GetMuted(context.Context, *GetMutedRequest) (*SpeakerMuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMuted not implemented")
}
func (UnimplementedAirPlayManagementServer) mustEmbedUnimplementedAirPlayManagementServer() {}
func (UnimplementedAirPlayManagementServer) testEmbeddedByValue()                           {}

// UnsafeAirPlayManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirPlayManagementServer will
// result in compilation errors.
type UnsafeAirPlayManagementServer interface {
	mustEmbedUnimplementedAirPlayManagementServer()
}

func RegisterAirPlayManagementServer(s grpc.ServiceRegistrar, srv AirPlayManagementServer) {
	// If the following call pancis, it indicates UnimplementedAirPlayManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AirPlayManagement_ServiceDesc, srv)
}

func _AirPlayManagement_ToggleBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirPlayManagementServer).ToggleBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirPlayManagement_ToggleBroadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirPlayManagementServer).ToggleBroadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirPlayManagement_ChangeServiceName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirPlayManagementServer).ChangeServiceName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirPlayManagement_ChangeServiceName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirPlayManagementServer).ChangeServiceName(ctx, req.(*NameChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirPlayManagement_ForwardToNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRemoveNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirPlayManagementServer).ForwardToNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirPlayManagement_ForwardToNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirPlayManagementServer).ForwardToNodes(ctx, req.(*AddRemoveNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirPlayManagement_RemoveForwardToNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRemoveNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirPlayManagementServer).RemoveForwardToNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirPlayManagement_RemoveForwardToNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirPlayManagementServer).RemoveForwardToNodes(ctx, req.(*AddRemoveNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirPlayManagement_GetCurrentTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirPlayManagementServer).GetCurrentTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirPlayManagement_GetCurrentTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirPlayManagementServer).GetCurrentTrack(ctx, req.(*GetTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirPlayManagement_GetMuted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMutedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirPlayManagementServer).GetMuted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirPlayManagement_GetMuted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirPlayManagementServer).GetMuted(ctx, req.(*GetMutedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AirPlayManagement_ServiceDesc is the grpc.ServiceDesc for AirPlayManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AirPlayManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.AirPlayManagement",
	HandlerType: (*AirPlayManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToggleBroadcast",
			Handler:    _AirPlayManagement_ToggleBroadcast_Handler,
		},
		{
			MethodName: "ChangeServiceName",
			Handler:    _AirPlayManagement_ChangeServiceName_Handler,
		},
		{
			MethodName: "ForwardToNodes",
			Handler:    _AirPlayManagement_ForwardToNodes_Handler,
		},
		{
			MethodName: "RemoveForwardToNodes",
			Handler:    _AirPlayManagement_RemoveForwardToNodes_Handler,
		},
		{
			MethodName: "GetCurrentTrack",
			Handler:    _AirPlayManagement_GetCurrentTrack_Handler,
		},
		{
			MethodName: "GetMuted",
			Handler:    _AirPlayManagement_GetMuted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobcaygeon.proto",
}
